# Generated by Django 4.0.4 on 2022-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_changeofownerdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='learnerpermitdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learners_name', models.CharField(max_length=100)),
                ('learners_dob', models.CharField(max_length=100)),
                ('learners_phone', models.CharField(max_length=100)),
                ('learners_email', models.CharField(max_length=100)),
                ('learners_address', models.CharField(max_length=100)),
                ('learners_state', models.CharField(max_length=100)),
                ('learners_routes', models.CharField(max_length=100)),
            ],
        ),
    ]
