# Generated by Django 4.0.4 on 2022-09-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_learnerpermitdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='renewaldetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_name', models.CharField(max_length=100)),
                ('license_dob', models.CharField(max_length=100)),
                ('license_gender', models.CharField(max_length=100)),
                ('license_phone', models.CharField(max_length=100)),
                ('license_email', models.CharField(max_length=100)),
                ('license_address', models.CharField(max_length=100)),
                ('license_state', models.CharField(max_length=100)),
                ('license_category', models.CharField(max_length=100)),
                ('license_use', models.CharField(max_length=100)),
                ('license_make', models.CharField(max_length=100)),
                ('license_model', models.CharField(max_length=100)),
                ('license_colour', models.CharField(max_length=100)),
                ('license_makeyear', models.CharField(max_length=100)),
                ('license_vehitype', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
                ('license_chasis', models.CharField(max_length=100)),
                ('license_engine', models.CharField(max_length=100)),
            ],
        ),
    ]
