# Generated by Django 4.0.4 on 2022-09-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_vehicleproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleproduct',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
