# Generated by Django 4.0.4 on 2022-09-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_vehicleproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vehicleproducts',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.vehicleproduct'),
        ),
    ]
