# Generated by Django 4.0.4 on 2022-09-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_order_vehicleproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vehicleproducts',
        ),
        migrations.CreateModel(
            name='Licenseorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vehicleproducts', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.vehicleproduct')),
            ],
        ),
    ]
