# Generated by Django 4.0.4 on 2022-09-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_remove_order_vehicleproducts_licenseorder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licenseorder',
            new_name='Learnersorder',
        ),
    ]
