# Generated by Django 4.0.4 on 2022-09-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_rename_licenseorder_learnersorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnersorder',
            old_name='vehicleproducts',
            new_name='vehicleproduct',
        ),
    ]
