# Generated by Django 4.0.4 on 2022-09-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_rename_vehicleproducts_learnersorder_vehicleproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnersorder',
            old_name='created',
            new_name='createdl',
        ),
    ]
