# Generated by Django 4.0.4 on 2022-09-29 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_ownerproduct_ownerorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learnerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnername', models.CharField(max_length=200)),
                ('learnerdescription', models.TextField(blank=True, null=True)),
                ('learnerimage_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('learnerprice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learnerorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learnercreated', models.DateTimeField(auto_now_add=True)),
                ('learnerproduct', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.learnerproduct')),
            ],
        ),
    ]
