# Generated by Django 3.2.16 on 2022-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_licenseproduct_licenseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email_pay', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
