# Generated by Django 4.0.4 on 2022-09-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createname', models.CharField(max_length=100)),
                ('createemail', models.CharField(max_length=100)),
                ('createusername', models.CharField(max_length=50)),
                ('createpassword', models.CharField(max_length=50)),
            ],
        ),
    ]
