# Generated by Django 4.0.4 on 2022-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posname', models.CharField(max_length=100)),
                ('bvn', models.CharField(max_length=100)),
                ('posemail', models.CharField(max_length=100)),
                ('posaddress', models.CharField(max_length=100)),
                ('posstate', models.CharField(max_length=100)),
            ],
        ),
    ]
