# Generated by Django 4.0.4 on 2022-09-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='changeofownerdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_fullname', models.CharField(max_length=100)),
                ('old_dob', models.CharField(max_length=100)),
                ('old_phone', models.CharField(max_length=100)),
                ('old_email', models.CharField(max_length=100)),
                ('old_address', models.CharField(max_length=200)),
                ('old_state', models.CharField(max_length=200)),
                ('new_fullname', models.CharField(max_length=100)),
                ('new_dob', models.CharField(max_length=100)),
                ('new_phone', models.CharField(max_length=100)),
                ('new_email', models.CharField(max_length=100)),
                ('new_address', models.CharField(max_length=100)),
                ('new_state', models.CharField(max_length=100)),
                ('new_use', models.CharField(max_length=100)),
                ('change_make', models.CharField(max_length=100)),
                ('change_model', models.CharField(max_length=100)),
                ('change_colour', models.CharField(max_length=100)),
                ('change_plate', models.CharField(max_length=100)),
                ('change_chasis', models.CharField(max_length=100)),
                ('change_engine', models.CharField(max_length=100)),
            ],
        ),
    ]
