# Generated by Django 4.0.4 on 2022-09-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_rename_description_vehicleproduct_ldescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learnersorder',
        ),
        migrations.DeleteModel(
            name='Vehicleproduct',
        ),
    ]
