# Generated by Django 4.0.4 on 2022-09-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_delete_learnersorder_delete_vehicleproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownerproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=200)),
                ('ownerdescription', models.TextField(blank=True, null=True)),
                ('ownerimage_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('ownerprice', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ownerorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownercreated', models.DateTimeField(auto_now_add=True)),
                ('ownerproduct', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.ownerproduct')),
            ],
        ),
    ]
